ANDROID: zram: Fix build issue with zram_can_store_pages w/o CONFIG_ZRAM_ANDROID_IOCTL
The zram_can_store_page() function was added in commit
160a4092db67 ("ANDROID: zram: Add
ZRAM_ANDROID_IOC_PROCESS_PREFETCH ioctl") but only used in logic
enabled w/ CONFIG_ZRAM_ANDROID_IOCTL.

This causes build errors when CONFIG_ZRAM_ANDROID_IOCTL is
disabled:

  error: unused function 'zram_can_store_page' [-Werror,-Wunused-function]

So wrap the new function in CONFIG_ZRAM_ANDROID_IOCTL as well.

Fixes: 160a4092db67 ("ANDROID: zram: Add ZRAM_ANDROID_IOC_PROCESS_PREFETCH ioctl")
Change-Id: I423302a7826b6c23230c60aa652e6cd38069c894
Signed-off-by: John Stultz <jstultz@google.com>