BACKPORT: ANDROID: Fix 32-bit kernelci build break
The fix for the ABI build-break was broken for 32-bit builds because the
struct sizes changed which tripped a static assertion checking size and
alignment of the KMI stable type. Since the KMI is not stable for
32-bit, resolve by suppressing this check for 32-bit builds.

Fixes the following KernelCI errors:
with gcc-14:
./include/linux/android_kabi.h:65:17: error: static assertion failed: "include/linux/dma-buf.h:547: u64 __kabi_reserved_backport1 is not aligned the same as atomic64_t nr_task_refs"
   65 |                 _Static_assert(                                         \
      |                 ^~~~~~~~~~~~~~
./include/linux/android_kabi.h:79:17: note: in expansion of macro ‘_ANDROID_KABI_NORMAL_SIZE_ALIGN’
   79 |                 _ANDROID_KABI_NORMAL_SIZE_ALIGN(_orig, _new); \
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/android_kabi.h:189:9: note: in expansion of macro ‘_ANDROID_KABI_REPLACE’
  189 |         _ANDROID_KABI_REPLACE(ANDROID_BACKPORT_RESERVE(number), _new)
      |         ^~~~~~~~~~~~~~~~~~~~~
./include/linux/dma-buf.h:547:9: note: in expansion of macro ‘ANDROID_BACKPORT_USE’
  547 |         ANDROID_BACKPORT_USE(1, atomic64_t nr_task_refs);
      |         ^~~~~~~~~~~~~~~~~~~~

with clang-21:
In file included from kernel/fork.c:110:
./include/linux/dma-buf.h:547:2: error: static assertion failed due to requirement '__alignof(struct dma_buf::(unnamed at ./include/linux/dma-buf.h:547:2)) <= __alignof(struct dma_buf::(unnamed at ./include/linux/dma-buf.h:547:2))': include/linux/dma-buf.h:547: u64 __kabi_reserved_backport1 is not aligned the same as atomic64_t nr_task_refs
  547 |         ANDROID_BACKPORT_USE(1, atomic64_t nr_task_refs);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/android_kabi.h:189:2: note: expanded from macro 'ANDROID_BACKPORT_USE'
  189 |         _ANDROID_KABI_REPLACE(ANDROID_BACKPORT_RESERVE(number), _new)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/android_kabi.h:79:3: note: expanded from macro '_ANDROID_KABI_REPLACE'
   79 |                 _ANDROID_KABI_NORMAL_SIZE_ALIGN(_orig, _new); \
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/android_kabi.h:66:4: note: expanded from macro '_ANDROID_KABI_NORMAL_SIZE_ALIGN'
   66 |                         __alignof__(struct { _new; }) <=                \
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   67 |                                 __alignof__(struct { _orig; }),         \
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/dma-buf.h:547:2: note: expression evaluates to '8 <= 4'
  547 |         ANDROID_BACKPORT_USE(1, atomic64_t nr_task_refs);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/android_kabi.h:189:2: note: expanded from macro 'ANDROID_BACKPORT_USE'
  189 |         _ANDROID_KABI_REPLACE(ANDROID_BACKPORT_RESERVE(number), _new)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/android_kabi.h:79:3: note: expanded from macro '_ANDROID_KABI_REPLACE'
   79 |                 _ANDROID_KABI_NORMAL_SIZE_ALIGN(_orig, _new); \
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/android_kabi.h:66:34: note: expanded from macro '_ANDROID_KABI_NORMAL_SIZE_ALIGN'
   66 |                         __alignof__(struct { _new; }) <=                \
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
   67 |                                 __alignof__(struct { _orig; }),         \
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC      arch/x86/entry/vdso/vma.o

Fixes: d66e9166bfa1 ("ANDROID: fix ABI-break in struct cgroup_root")
Signed-off-by: Todd Kjos <tkjos@google.com>
[ynaffit: updated commit message for new break]
Fixes: b1ac27dd8a57 ("ANDROID: ABI: refresh, CRC fixups and allowed breaks")
Change-Id: Ied0ca3e4d892014582c921d311fdab652a76adf6
(cherry picked from commit fa2752f439942a680289ebfcc83a4ae05282e5a7)
Signed-off-by: Tiffany Yang <ynaffit@google.com>