ANDROID: binder: fix build error when CONFIG_EVENT_TRACING=n
Fix below build error when CONFIG_EVENT_TRACING=n

aarch64-none-linux-gnu-ld: Unexpected GOT/PLT entries detected!
aarch64-none-linux-gnu-ld: Unexpected run-time procedure linkages detected!
aarch64-none-linux-gnu-ld: drivers/android/binder.o: in function `binder_remove_trace_events':
binder.c:(.text+0x1bcc): undefined reference to `event_mutex'
aarch64-none-linux-gnu-ld: drivers/android/binder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `event_mutex' which may bind externally can not be used when making a shared object; rec
ompile with -fPIC
binder.c:(.text+0x1bcc): dangerous relocation: unsupported relocation
aarch64-none-linux-gnu-ld: binder.c:(.text+0x1bd0): undefined reference to `event_mutex'
aarch64-none-linux-gnu-ld: binder.c:(.text+0x1be8): undefined reference to `trace_types_lock'
aarch64-none-linux-gnu-ld: drivers/android/binder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `trace_types_lock' which may bind externally can not be used when making a shared object
; recompile with -fPIC
binder.c:(.text+0x1be8): dangerous relocation: unsupported relocation
aarch64-none-linux-gnu-ld: binder.c:(.text+0x1bec): undefined reference to `trace_types_lock'
aarch64-none-linux-gnu-ld: binder.c:(.text+0x1bf0): undefined reference to `trace_event_sem'
aarch64-none-linux-gnu-ld: drivers/android/binder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `trace_event_sem' which may bind externally can not be used when making a shared object;
 recompile with -fPIC
binder.c:(.text+0x1bf0): dangerous relocation: unsupported relocation
aarch64-none-linux-gnu-ld: binder.c:(.text+0x1bf8): undefined reference to `trace_event_sem'
aarch64-none-linux-gnu-ld: binder.c:(.text+0x1c08): undefined reference to `ftrace_events'
aarch64-none-linux-gnu-ld: drivers/android/binder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `ftrace_events' which may bind externally can not be used when making a shared object; r
ecompile with -fPIC
binder.c:(.text+0x1c08): dangerous relocation: unsupported relocation
aarch64-none-linux-gnu-ld: binder.c:(.text+0x1c0c): undefined reference to `ftrace_events'
aarch64-none-linux-gnu-ld: binder.c:(.text+0x1c10): undefined reference to `ftrace_events'
aarch64-none-linux-gnu-ld: binder.c:(.text+0x1ca8): undefined reference to `remove_event_from_tracers'

Bug: 481833411
Fixes: 43c26111cafa ("ANDROID: binder: unload C Binder trace events")
Change-Id: Idc13dbf0272c85353d0e24bfca4f88b1fc001403
Signed-off-by: Jisheng Zhang <jszhang@kernel.org>